### ISSUE TITLE
Not an issue but a question: How did you manage to deploy the backend the netlify

### ISSUE THREAD

**Issue by 01231** [ozgrozer/tweet-image#3]
Did you deploy the backend to netlify too or did you only deploy the frontend to netflify and the backend to something like heroku?

**Comment by ozgrozer** [comment]
It's on Glitch and Heroku. Frontend and backend are in the same place.

https://tweet-image.glitch.me/
https://tweet-image.herokuapp.com/

**Comment by 01231** [comment]
Thanks for the answer!
